# ./config/auth0.yml
development:
    auth0_domain: {{AUTH0_DOMAIN}}
    auth0_client_id: {{AUTH0_CLIENT_ID}}
    auth0_client_secret: {{AUTH0_CLIENT_SECRET}}

production:
    auth0_domain: {{AUTH0_DOMAIN}}
    auth0_client_id: {{AUTH0_CLIENT_ID}}
    auth0_client_secret: {{AUTH0_CLIENT_SECRET}}